### ISSUE TITLE
Can rake-compiler be a development dependency?

### ISSUE THREAD

**Issue by joshuaflanagan** [SamSaffron/fast_stack#5]
I just added the flamegraph gem to my project, and noticed that rake-compiler was brought in via fast_stack.

I'm not familiar with how rake-compiler works, but I get the feeling it should only be needed by the fast_stack gem authors, which should make it a good candidate for `add_development_dependency` in the `gemspec`. It would be nice to reduce the gem footprint for anyone pulling in this `fast_stack`.

**Comment by SamSaffron** [comment]
Interesting can you try removing it and see if the gem installs right, I
though it is required for the compilation phase cause we do not ship
binaries
